//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXI_New_Hire_Survey_Tool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lobs
    {
        public int LobId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public string DateCreated { get; set; }
        public string UpdatedBy { get; set; }
        public string DateUpdated { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
