//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXI_New_Hire_Survey_Tool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogVisit
    {
        public int Id { get; set; }
        public string Hrid { get; set; }
        public string CountryCode { get; set; }
        public string SiteCode { get; set; }
        public string ProgramCode { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
