//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXI_New_Hire_Survey_Tool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VXI_NEW_HIRE_SURVEYEntities : DbContext
    {
        public VXI_NEW_HIRE_SURVEYEntities()
            : base("name=VXI_NEW_HIRE_SURVEYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SurveyQuestion> SurveyQuestion { get; set; }
        public virtual DbSet<SurveyChoices> SurveyChoices { get; set; }
        public virtual DbSet<SurveyAnswer> SurveyAnswer { get; set; }
        public virtual DbSet<SurveyAnswer_info> SurveyAnswer_info { get; set; }
        public virtual DbSet<UserManage> UserManage { get; set; }
        public virtual DbSet<BroadcastManage> BroadcastManage { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Lobs> Lobs { get; set; }
        public virtual DbSet<Respondents> Respondents { get; set; }
        public virtual DbSet<DateSystemUpdate> DateSystemUpdate { get; set; }
        public virtual DbSet<LogVisit> LogVisit { get; set; }
    }
}
