//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXI_New_Hire_Survey_Tool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respondents
    {
        public int Id { get; set; }
        public string Hrid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string HireDate { get; set; }
        public string Department { get; set; }
        public string Email { get; set; }
        public string Team { get; set; }
        public string Project { get; set; }
        public string Region { get; set; }
        public string Site { get; set; }
        public string SupervisorID { get; set; }
        public string PositionLevel { get; set; }
        public string NtAccount { get; set; }
        public string DateCreated { get; set; }
        public string Status { get; set; }
    }
}
