//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXI_New_Hire_Survey_Tool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyChoices
    {
        public int Id { get; set; }
        public string TypeDescription { get; set; }
        public string Choices { get; set; }
        public string DateCreated { get; set; }
        public string CreatedBy { get; set; }
    }
}
