//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXI_New_Hire_Survey_Tool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyAnswer_info
    {
        public int Id { get; set; }
        public string ResponseId { get; set; }
        public string HRID { get; set; }
        public string TL_HRID { get; set; }
        public string Comment { get; set; }
        public string DateCreated { get; set; }
        public string Trainor_Fullname { get; set; }
        public string SupervisorId { get; set; }
        public string Department { get; set; }
        public string Team { get; set; }
        public string Site { get; set; }
        public string HireDate { get; set; }
    }
}
