//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXI_New_Hire_Survey_Tool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserManage
    {
        public int Id { get; set; }
        public string HRID { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string LOB { get; set; }
        public string Position { get; set; }
        public string Site { get; set; }
        public string Position_Level { get; set; }
        public string Roles { get; set; }
        public string Createdby { get; set; }
        public string UpdatedBy { get; set; }
        public string DateCreated { get; set; }
        public string DateUpdated { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string NTAccount { get; set; }
        public string HireDate { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> isSentEmail { get; set; }
    }
}
